### PR TITLE
Fixed quote escaping in SQL queries for Hefe names in recipes.

### PR DESCRIPTION
**Pull request by frsteinb**
We need SQL escaping instead of HTML here.

### CODE REVIEW

**Comment by bitwave** [comment]
Maybe use prepared statements, as in f05a85e6939f9b3aaa3659babb05a46ec4e63540.
This prevents these errors.

**Comment by frsteinb** [comment]
I would be happy with whatever solution looks best to the more experienced contributors. The commit of this pull request seemed to fix the problem at least for me at first sight.

Please note that there are *many* occurrences of " sql = ... .replace("'", "''") ... " throughout the code.

**Comment by bitwave** [comment]
Prepared Statements are the best and most often fastest way to circumvent SQL injections.

**Comment by bitwave** [comment]
You can use this here:

```C
      QSqlQuery query;
      query.prepare("SELECT TypTrFl FROM Hefe WHERE Beschreibung=:beschreibung");
      query.bindValue(":beschreibung", AuswahlHefe);
      if (!query.exec()) {
        // Fehlermeldung Datenbankabfrage
        ErrorMessage *errorMessage = new ErrorMessage();
        errorMessage -> showMessage(ERR_SQL_DB_ABFRAGE, TYPE_WARNUNG,
                                    CANCEL_NO, trUtf8("Rückgabe:\n") + query_Hopfen.lastError().databaseText()
                                    + trUtf8("\nSQL-Befehl:\n") + query.lastQuery());
```

easier to read, safe and no need for html or replaces.

**Comment by BourgeoisLab** [comment]
Prepared statements are indeed the best. Thanks biwave. But as you reported, there are so many of these SQL queries to change...

**Pull request merged**
