### PR TITLE
Preserve symlinks when creating ZIP

### PR DESCRIPTION
**Pull request by m-schmidt**
This should fix the problem of WebViews (Spickzettel, Anleitung) not displaying anything. The problem was caused by expanding symlinks within the embedded Qt-Frameworks to actual files during zipping the binary.

### CODE REVIEW

**Comment by m-schmidt** [comment]
Holger also managed to activate localization.

**Comment by BourgeoisLab** [comment]
Thanks for the night update. What a shitty bug with the symlinks...

In the "close application" dialog do you see the buttons in German if set to German?
If they are in English you need to generate and copy qt_de.qm to the language folder! Here the manual 
http://doc.qt.io/qt-5/linguist-programmers.html#deploying-translations

For linux I do this
`"$QT_DIR/lconvert" -o "$DEPLOY_DIR/usr/local/bin/kleiner-brauhelfer/languages/qt_de.qm" "$QT_DIR/../translations/qtbase_de.qm"`

In your case "$DEPLOY_DIR/usr/local/bin/kleiner-brauhelfer/languages/qt_de.qm" is "${BUNDLE}/Contents/MacOS/languages/qt_de.qm".

OR if qt_de.qm is already generated with macdeployqt, just copy the file to the language folder.
`mv "${BUNDLE}/Contents/MacOS/qt_de.qm" "${BUNDLE}/Contents/MacOS/languages"`
or similiar.
Even better
`mv "${BUNDLE}/Contents/MacOS/*.qm" "${BUNDLE}/Contents/MacOS/languages"`

**Comment by m-schmidt** [comment]
I can test this later today if you postpone merging, e.g until tomorrow.

**Comment by BourgeoisLab** [comment]
Just tell me when its ready for merging.

**Comment by realholgi** [comment]
for those interested: I now upload the macOS (pre)release builds to my "Releases" page: https://github.com/realholgi/kleiner-brauhelfer/releases

**Comment by m-schmidt** [comment]
I totally forgot this. I think it can be merged.

**Pull request merged**
